### ISSUE TITLE
[ Bug ? ] Arent you forget file "BepInEx\plugins\DanW-SPTQuestingBots\quests\standard\customs.json" ?

### ISSUE THREAD

**Issue by 6562680** [dwesterwick/SPTQuestingBots#34]
Most of times playing at Customs. Questing Bots forces PMCs to keep some building or bush area and sit there until am going alongside.

Worse than circle running bots may be only group of 3 pmcs that is holding bushes until you reach them.

**Comment by 6562680** [comment]
No, i see the logs `bigmap.json` seems the bots is solving some quests

But actually it seems as nothing

I have SWAG/DONUTS/SAIN enabled, start-pmc-only and raids becomes to 2 types: all damn pmcs spawned in maybe 500 meters in natural customs spawns, they hear shoots and it becomes to fight, and of course damn bots tries to kill me first, then shoot each other, once i saw that bots from different squads, even scavs fight together vs me, just wipe in first 30 seconds.

If i survive first minute of the game - then bots time to time running at 100 meters from be between bushes like biting me to shoot, but i cant feel it like they're questing. 20% of bots running somewhere, others - hold some factory building or area of bushes.

Few bots even spawned UNDERWATER at customs river and wait there for whole round.

**Comment by dwesterwick** [comment]
If you need help with configuring mods, please ask either on the mod's comment page on the [SPT hub](https://hub.sp-tarkov.com/) or in the SPT Discord. 

There are a two main reasons you're having this experience:
1. By default, SAIN takes priority over Questing Bots, so bots will wait until they no longer detect nearby enemies before they start (or resume) questing. If you don't like how SAIN controls bots in combat or when searching/waiting for enemies, you can configure that mod to your liking. 
2. If you're using SWAG+DONUTS, it will control spawning, not this mod. This mod disables its spawning system when SWAG is installed. SWAG+DONUTS is currently undergoing a significant rewrite, so please do not expect a perfect experience until that is complete. 

Because neither of these point to a bug with this mod, I'm closing this issue.
