### ISSUE TITLE
[ Feature Request ] Despawn bots that is disabled for a certain time

### ISSUE THREAD

**Issue by 6562680** [dwesterwick/SPTQuestingBots#37]
The `Tarkov Streets` map on my PC is required to restrict bots, `dvize.Donuts` spawns bots anywhere (even with my configs on raid start its required to spawn with 100% chance scav snipers and bosses, and the Donuts has no "botType" field, so somewhere it spawns regular bots somewhere instead of snipers), and I have bot restriction enabled in SWAG. So I have max 8 SCAV bots, and half of them spawn about a kilometer away from me (the `Dynamic Maps` mod shows positions), and these bots stay for the whole game waiting for me.

It would be nice to despawn bots that stay disconnected for 30 seconds or so (allowing `donuts` to spawn new bots).

`dvize.Donuts` have its own despawn timer and engine. The trouble is in that this engine is working only if donuts spawn more bots that allowed by limit (spawn 3 groups with 5 bots with limit of 10, 5 bots will be removed). It select bot at longest distance and removes it. But most of the times bots is spawned inside limit and bots on long distance just stay without action blocking the slot.

Btw, `dvize.Donuts` is very... non-logical, maybe buggy, but very stable package.

**Comment by dwesterwick** [comment]
Maybe I'm misunderstanding, but wouldn't this be more of a DONUTS issue? If you're using SWAG, this mod's spawning system is completely disabled. Therefore, it wouldn't make sense for it to interact with whatever spawning system is being used. That would just add confusion.

**Comment by 6562680** [comment]
Yes, its a Donuts issue, bot it is a forgotten plugin, so i hope you can solve it while improving limitation feature

**Comment by dwesterwick** [comment]
Sorry, that's outside the scope of this mod. If another spawning mod is used, I don't think this mod should interact with it at all. Even with the spawning system in this mod, my objective is to create a live-like experience, and in that case some bots will stay on the other side of the map from you. I never intended this mod to be an alternative to SWAG+DONUTS.

**Comment by 6562680** [comment]
Am fucking tired of about any modmaker always say "is out of scope" for any feature that fix common bugs really.

Why i must learn how to create mods just because nobody wants to help each other.

**Comment by dwesterwick** [comment]
You're asking me to fix an issue with another person's mod, for free, when I already have limited time to spend on hobbies like this. You're welcome to propose ideas, but I think it's completely reasonable for me to decline. 

Also, I have to point out the irony in you complaining about nobody wanting to help each other when you admit that you're an experienced developer and aren't interested in contributing to the community by creating your own mods to solve the common problems you're experiencing. That's why I started (without any prior experience with Unity or TypeScript), along with many other modders.
