### ISSUE TITLE
Add chance to have no quest and become a looting wonderer.

### ISSUE THREAD

**Issue by Rsslone** [dwesterwick/SPTQuestingBots#8]
So I've been tinkering with the values to kind of solve my FPS problem, I can't say if its specifically the questing bot AI, I think it might just be the action going on. Thought the idea of just reverting say half the bots to being looters and not quest at all might help.

If you have any other quick tips to claw back some performance without hurting the experience, I'd love to hear.

**Comment by dwesterwick** [comment]
I can see some value in a compromise solution of keeping some bots in "hotspot" locations, but I'm sure you can understand how this is antithetical to the idea behind this mod. I'll think about your suggestion, but I'd rather try to identify the cause(s) of your performance issues first.

I would recommend trying the following:
* If you're not already, please try the built-in AI limiter. For most people, it makes a very noticeable improvement. 
* When you're experiencing performance issues, you can try completely disabling questing for bots in the Questing Bots F12 menu. For my somewhat-older PC, I'm only seeing a ~5 fps hit with questing enabled during a full Customs raid (without using the AI limiter). If you're seeing a much higher drop (20+ fps), there might be some issue we should troubleshoot.

If you're still struggling to identify the source of the performance issues, please feel free to ask for support in the Questing Bots thread in the SPT Discord.

**Comment by Rsslone** [comment]
Thanks for the response, I'll just mention that disabling the questing bot logic for a number of bots wouldn't keep them in hotspot locations if the user is running looting bots right? Their mission would become to loot and extract at that point no?

I have a mid-high end PC (12600k / 4070 Ti), and it feels like my FPS is well below 45 on raid start, but gets better over a few minutes after AI die. I think its just the number of early engagements that happen. I'll try the AI limiter and see how it goes.

**Comment by dwesterwick** [comment]
Disabling questing would only be for testing the performance impact, not for playing that way. 

If your performance improves after the first few minutes of a raid, you might be trying to spawn too many bots. Other mods like SAIN and Looting Bots also have a performance impact, so the effect compounds. 

Currently, Questing Bots only supports SPT, so the AI limiter probably won't work correctly with MPT. I've never tried though.

**Comment by Rsslone** [comment]
Just to clarify, my suggestion is to basically have some bots not added to the questing bots brain layer (or whatever), so they would act like questing bots was disabled. The reason I think this might be useful is questing bots tend to get in more fights sooner. Which early on (I think) causes some lag. Its a fringe thing, and if its hard to implement, no worries.

On another note, if you could specify, I'm having an issue where I've not seen a single boss spawn (and there is a support thread in MPT's discord), Does the spawn bosses first work if you're using the advanced spawning system, the wording of your description was a little confusing to me.

**Comment by dwesterwick** [comment]
I understand your suggestion, but I feel like the better solution is to address the small period of lag instead of completely disabling questing for some bots. There are a few reasons for this:
* It would be difficult to identify which bots need to stop questing for the purpose of mitigating the lag (if it's related to combat)
* This may suggest better quest-selection balancing is needed for some maps
* For some people, especially those with older machines, this problem can be easily mitigated by reducing the number of bots which initially spawn
* Like I mentioned, a feature like that would be antithetical to the idea behind this mod
* Selfishly, I would get complaints about some PMC's not questing (which I already get complaints about)

If there's another reason for your suggestion that's unrelated to the lag issue, I might just not be understanding it. The only change I can think of is applying long breaks in questing when bots reach defined "hotspot" locations so it's more likely that you'll encounter them when you go there. However, if you're using Looting Bots and have a high search radius, they might wander off anyway, so I'm not sure how effective (or beneficial) this would be. 

With the Questing Bots advanced spawning system, PMC spawns occur in parallel with EFT boss spawns.

**Comment by Rsslone** [comment]
At the end of the day the reason would be lag related, but I do think it'd be interesting to just have a few loot goblins wondering without a goal. That's pretty much the only other reason in favor of it.

**Comment by dwesterwick** [comment]
Gotcha. I do plan to implement a hidden-stash runner quest type in the future, so that will still happen.

Sorry.
